name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job: #Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu
    steps:
      - name: Checkout code
        run: git clone https://github.com/berezovsky13/nodejs.git  # Gets the latest code, in other words it does 'git clone' 
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!" # This is just the command
      - name: ping to google
        run: curl -I https://www.google.com
      - name: List files and directories
        run: ls -la
      - name: rub bash script
        run:  |
          echo '#!/bin/bash' > show_time_in_israel.sh
          echo 'export TZ="Asia/Jerusalem"' >> show_time_in_israel.sh
          echo 'date' >> show_time_in_israel.sh
          chmod +x show_time_in_israel.sh
          ./show_time_in_israel.sh # Run the script
